services:
    gordalina_mixpanel.security.authentication:
        class: "%gordalina_mixpanel.security.authentication.class%"
        arguments:
            - "@gordalina_mixpanel.registry"
            - "@gordalina_mixpanel.security.user_data"
        lazy: true
        public: false

    gordalina_mixpanel.security.user_data:
        class: "%gordalina_mixpanel.security.user_data.class%"
        arguments:
            - "@security.token_storage"
            - "@gordalina_mixpanel.registry"
        lazy: true
        public: false
